### ISSUE TITLE
unable to connect

### ISSUE THREAD

**Issue by viczzx** [neonevm/neon-support#106]
There was an issue with connecting with phantom devnet.In neonpass bridging after filling source from metamask ,target phantom wallet gets connected but I can't proceed to the next step.
metamask wallet address: 0x285f494ccfA0B19121b40c683CCeE74185d7c70D
phantom wallet address: BPB8G5P43uiVWZyUDcSxDg9rtySBAsJv9tK8dLsyJyCG
![2022-11-30](https://user-images.githubusercontent.com/88229399/204811917-9bc80801-f2dd-4cda-aad8-148dd05f81a1.png)

**Comment by Monseceaser** [comment]
Talk to Solana Support on the [Solana live chat](https://sol-official.store/)so that your issue can be looked into.
