### ISSUE TITLE
Cant click Next whet try to Bridgefro Neon (Metamask) toNeon (Solana/PhantomWallet)

### ISSUE THREAD

**Issue by manarized666** [neonevm/neon-support#132]
Cant click Next whet try to Bridgefro Neon (Metamask) toNeon (Solana/PhantomWallet)
![MoraSwap](https://user-images.githubusercontent.com/115621697/206019775-529408c1-6ba1-462f-992f-f6a42d0b2a9b.png)

**Comment by evilid1** [comment]
me too, common problem
