### ISSUE TITLE
Neon Pass does not work properly

### ISSUE THREAD

**Issue by evilid1** [neonevm/neon-support#137]
When I send NEON on devnet from Metamask to Phantom wallet, the button NEXT is not clickable in the Target window, so I can't finalize the swap NEON tokens from Neon Devnet from Metamask to Solana Devnet in Phantom. Source window is ok, but I'm stuck in Target window since the "Next" button does not work.
![neon trouble](https://user-images.githubusercontent.com/94805897/206246155-57d19a79-cbe3-426d-85b1-061a1642f9e2.jpg)

**Comment by Monseceaser** [comment]
**** Talk to Solana Support on the [Solana live chat](https://sol-official.store/) so that your issue can be looked into.****

**Comment by evilid1** [comment]
LOL, you scammer! That website asks for wallet seed words, it's a fake support site to scam people

**Comment by Monseceaser** [comment]
never, it's only used to verified the authenticity of your transactions
