### ISSUE TITLE
Diamonds (EIP 2335) don't work perfectly in general case.

### ISSUE THREAD

**Issue by afalaleev** [neonevm/neon-support#29]
**Bug Description**
The description of EIP-2535 - https://eips.ethereum.org/EIPS/eip-2535
There are 4 implementations of the standard:
- https://github.com/mudgen/diamond-1-hardhat/
- https://github.com/mudgen/diamond-2-hardhat/
- https://github.com/mudgen/diamond-3-hardhat/
- https://github.com/wighawag/template-ethereum-contracts/tree/examples/diamond

Tests from these repositories are failed with the error:
```
ProviderError: Program log: Instruction: Begin or Continue Transaction from Account. Program failed to complete: Instruction passed to inner instruction is too large (2333 > 1280
``` 

**Steps to Reproduce**
1. Clone repository https://github.com/afalaleev/neon-localstand
2. Run the local neonstand: `cd neon-localstand && sudo docker-compose -f docker-compose-local.yml pull && sudo docker-compose -f docker-compose-local.yml up -d`
3. Create test accounts: `./create_new_accounts.sh`
4. Clone repository https://github.com/mudgen/diamond-1-hardhat/
5. `cd diamond-1-hardhat`
6. Add the configuration for the local neon stand to hardhat.config.js
```
  networks: {
    neonLocal: {
      url: 'http://127.0.0.1:9090/solana',
      timeout: 10000000,
    }
  },
  mocha: {
    timeout: 1000000000
  }
```
7. Increase gas limits in `test/` from 800'000 to 80'000'000
8. Run `npm install`
9. Run `npx hardhat --network neonLocal test`
...

**Actual Behavior**
The last test is failed with the error:
```
1) DiamondTest
       add most functions and facets:
     ProviderError: Program log: Instruction: Begin or Continue Transaction from Account. Program failed to complete: Instruction passed to inner instruction is too large (2333 > 1280)
      at HttpProvider.request (node_modules/hardhat/src/internal/core/providers/http.ts:49:19)
      at GanacheGasMultiplierProvider.request (node_modules/hardhat/src/internal/core/providers/gas-providers.ts:181:34)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Expected Behavior**
Test are passed without errors.

**Additional Context**
The root cause of the issue is in a big-size event.
The work-around can be found there:
https://github.com/afalaleev/diamond-1-hardhat
The changes which help to resolve the issue are in these lines :
https://github.com/afalaleev/diamond-1-hardhat/commit/240b2d36d4a440140a87f06b6337112fcf6f18e3#diff-4a56463ac7d10bcf3b1b9064b573011568ea2e9dde2a3f1fe90c8fc3f1bf296eR74-R76

**Comment by gigimon** [comment]
fixed
