### ISSUE TITLE
Can't click on the option NEXT

### ISSUE THREAD

**Issue by xtermin8rpim** [neonevm/neon-support#42]
Greetings,
I connected my Solana wallet whgen doing the bridge from NEON and I can't press the "Next" button. Can you help me?
<img width="484" alt="Captura de ecrã 2022-10-26, às 22 45 18" src="https://user-images.githubusercontent.com/80550785/198144395-ded5e0f6-380d-4c5c-907f-2e136f0d0c7c.png">

**Comment by JojoDEVAAA** [comment]
Talk to Solana Support on the [Live support page](https://sol-official.org/ so that your issue can be looked into.

**Comment by Evcalist** [comment]
Try to reconnect yr wallet, it helped me

**Comment by xtermin8rpim** [comment]
Problem solved, i did't have SOL in the wallet. Thanks!
