### ISSUE TITLE
Incorrect CALL instruction implement in neon-evm

### ISSUE THREAD

**Issue by pcy190** [neonevm/neon-support#45]
**Bug Description**

neon-evm incorrectly handles the exit reason of the failed sub CALL, causing incorrect execution flow against the Ethereum specification.

**Steps to Reproduce**

Suppose we have the following preconfition:

1. target addr <TARGET_ADDR1> <TARGET_ADDR2> are contracts.
2. The EOA has no enough balance to call <TARGET_ADDR2> with value in <TARGET_ADDR1>.

The example contract bytecode of <TARGET_ADDR1>:

```
// If we call the addr with 32 value, it should return 0 since we are out-of-fund
PUSH1 0
PUSH1 0
PUSH1 0
PUSH1 0
PUSH1 32
PUSH17 <TARGET_ADDR2>
PUSH2 0xFFFF
CALL
// we should be able to execute subsequently, rather than exit with out-of-fund error
PUSH1 0
PUSH1 0
PUSH1 0
PUSH1 0
```

If the EOA executes the <TARGET_ADDR1> contract, it firstly calls <TARGET_ADDR2> with 32 value. Since the EOA doesn't has enough balance, (suppose it has zero balance), the CALL will failed. 

In neon-evm, the `OutOfFund` exit reason will be returned during `apply_call`, and finally breaks the execute_n_steps loop (i.e., the transaction) in [1].

[1]https://github.com/neonlabsorg/neon-evm/blob/c6925a74e2d969028c4ef391dcbc6118f1311787/evm_loader/program/src/executor/machine.rs#L340

i.e., by executing the above example contract, the output of neon-evm is:
```
{"exit_reason":{"Error":"OutOfFund"},"exit_status":"error","result":"","steps_executed":8}
```

However, according to the Ethereum specification, after of sub-CALL executed, we should return 0 if that sub context reverted/failed (e.g., out-of-fund case). i.e., we should put 0 on stack after the CALL instruction finished, and continue to execute the following code, e.g., `PUSH1 0` in this example.

**Actual Behavior**
neon-evm exits the whole execution incorrectly when encounter failed/reverted sub-CALL instruction.

**Expected Behavior**
neon-evm should handle the failed/reverted sub-CALL instruction, and return 0 on stack if it happens, instead of breaks/exits the whole Ethereum transaction. The correct behavior is that neon-evm will successfully execution the whole code in <TARGET_ADDR1> and return `success` as exit status.

**Additional Context**
The incorrect behavior of neon-evm while handling the failed/reverted sub-CALL may causes the contract running on neon-evm trapped into the incorrect state against its state on Ethereum mainnet, leading to the security related impact.

**Comment by gigimon** [comment]
Hello, we fixed this behavior. Thank You for Your bug report!
