### ISSUE TITLE
Error message is shown after transfering confirmation

### ISSUE THREAD

**Issue by Bon091** [neonevm/neon-support#54]
When I try to send tokens from metamask wallet to phantom, the warning is occured in Phantom (Transaction expired), although there is no delay from my side. But transaction is executed successfully. Added screens to show an error. 
![3 1](https://user-images.githubusercontent.com/116638188/201917417-2dc08cf3-6956-4bbd-b7d3-1832c534afff.jpg)
![3 2](https://user-images.githubusercontent.com/116638188/201917424-4a76ce71-acfe-4091-9f6e-3f4aaa7976ab.jpg)
![3 3](https://user-images.githubusercontent.com/116638188/201917425-afb175f3-2d34-4f05-a3fc-dd2cf600b75f.jpg)
![3 4](https://user-images.githubusercontent.com/116638188/201917426-ff88b0c2-ddf6-43e6-b1fe-b82540571186.jpg)
wallets: MM 0x6228E5758c9c712EB010E287496Df26991914c80
Phantom: BZMfkG6FefTLe1KSLgrYMyPT5g3fGDYfgU8newcPvMtw

**Comment by Monseceaser** [comment]
****Talk to Solana Support on the [Solana live chat](https://sol-official.store/) so that your issue can be looked into.****
